In [7]:
#create pandas series

In [12]:
#Import pandas
import pandas as pd

In [13]:
#create pandas series using list

data = [10,20,30,40]
series = pd.Series(data)
print(series)

0    10
1    20
2    30
3    40
dtype: int64


In [15]:
# create series using a custom index
data = [1,2,3,4]
i = ['A','B','C','D']
series=pd.Series(data,index=i)
print(series)

A    1
B    2
C    3
D    4
dtype: int64


In [17]:
data={'a':10,'b':20,'c':30}
series = pd.Series(data)
print(series)


a    10
b    20
c    30
dtype: int64


In [18]:
series.replace(20,40)

a    10
b    40
c    30
dtype: int64

## Pandas Dataframe

In [22]:
#create pandas dataframe from dictionary of lists
import pandas as pd

data={'Name':['Alice','Bob','Mary'],'Age':[25,30,34],'Country':["USA","UK","AUS"]}
df = pd.DataFrame(data)
print(df)

    Name  Age Country
0  Alice   25     USA
1    Bob   30      UK
2   Mary   34     AUS


In [23]:
#create pandas dataframe from numpy array

In [29]:
import numpy as np

array = np.array([[3,1,8], [9,1,9],[3,4,5]])
print(array)
df = pd.DataFrame(array, columns=['A','B','C'])
print(df)

[[3 1 8]
 [9 1 9]
 [3 4 5]]
   A  B  C
0  3  1  8
1  9  1  9
2  3  4  5


In [28]:
#create pandas dataframe from dictionary of lists
import pandas as pd

data={'Name':['sai','sathwik','Arun'],'Age':[25,30,34],'Country':["USA","UK","AUS"]}
df = pd.DataFrame(data)
print(df)

      Name  Age Country
0      sai   25     USA
1  sathwik   30      UK
2     Arun   34     AUS


In [26]:
#create pandas dataframe from numpy array

In [27]:
import numpy as np

array = np.array([[1,2,3], [4,5,6],[7,8,9]])
print(array)
df = pd.DataFrame(array, columns=['A','B','C'])
print(df)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9
